"""
Django settings for Blog project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
from .dev_settings import GOOGLE_PASSWORD, YANDEX_PASSWORD

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@y_8*c^j1trq)=68*!9)85gg$n-80vb1d_0sd6-atkqag85e!8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'account',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

MIDDLEWARE_CLASSES = [
    'account.middleware.LocaleMiddleware',
    'account.mibbleware.TimezoneMiddleware',
    'account.middleware.ExpiredPasswordMiddleware',
]

ROOT_URLCONF = 'Blog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [str(BASE_DIR.joinpath('templates'))],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'account.context_processors.account',
            ],
        },
    },
]

LOGIN_REDIRECT_URL = ''
LOGOUT_REDIRECT_URL = ''

ACCOUNT_UNIQUE_EMAIL = False #Уникальный адрес электронной почты учетной записи
ACCOUNT_EMAIL_CONFIRMATION_REQUIRED = True #Требование подтверждения электронной почты учетной записи
EMAIL_CONFIRMATION_UNIQUE_EMAIL = False

ACCOUNT_USER_DISPLAY = lambda user: user.email #Отображение учетной записи пользователя
ACCOUNT_PASSWORD_EXPIRY = 60*60*24*7 #Истечение срока действия пароля учетной записи
ACCOUNT_PASSWORD_USE_HISTORY = True #История использования пароля учетной записи

TEST_RUNNER = "accounts.tests.MyTestDiscoverRunner" #Запуск тестов

WSGI_APPLICATION = 'Blog.wsgi.application' #Приложение WSGI

SITE_ID = 2

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' #Серверная часть электронной почты
EMAIL_HOST = 'smtp.gmail.com' #Хост электронной почты
EMAIL_HOST_USER = 'suiginto1996@gmail.com' #Пользователя хоста электронной почты
EMAIL_HOST_PASSWORD = GOOGLE_PASSWORD #Пароль пользователя хоста электронной почты
EMAIL_PORT = 587 
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'support@BlogForProgrammers.ru'



EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_HOST_USER = 'djangorestframework@yandex.ru'
EMAIL_HOST_PASSWORD = YANDEX_PASSWORD
EMAIL_PORT = 587
EMAIL_USE_TLS = True

AUTHENTICATION_BACKENDS = [
    'account.auth_backends.EmailAuthenticationBackend',
]       #Серверы аутентификации

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
